<?php

use Illuminate\Database\Seeder;

class NewsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('news')->insert([
            ['category_news_id' => 1, 'c_name' => 'Lộ giá bán các phiên bản Xiaomi Mi MIX 3: Từ 11.7 triệu đồng', 'c_content' => '<p>Mới đ&acirc;y, một bức ảnh r&ograve; rỉ cho thấy gi&aacute; b&aacute;n của nhiều phi&ecirc;n bản smartphone Mi MIX 3 &ndash; si&ecirc;u phẩm m&agrave;n h&igrave;nh kh&ocirc;ng viền cạnh sắp ra mắt của&nbsp;Xiaomi.</p>\r\n', 'c_date' => '2018-07-07 21:54:00', 'c_img' => '15309926931530992693mix-3-3_800x450.jpg', 'c_hotnews' => 1, 'c_description' => '<p>Về thiết kế, sẽ c&oacute; 2 biến thể kh&aacute;c nhau, biến thể ti&ecirc;u chuẩn v&agrave; biến thể vỏ gốm. Bản ti&ecirc;u chuẩn sẽ trang bị &ldquo;camera n&acirc;ng&rdquo;, hay c&ograve;n gọi l&agrave; camera pop-up nằm ẩn ở viền cạnh tr&ecirc;n. Model n&agrave;y được liệt k&ecirc; với c&aacute;c phi&ecirc;n bản bộ nhớ RAM + ROM kh&aacute;c nhau gồm:</p>\r\n\r\n<ul>\r\n	<li>6 GB + 64 GB gi&aacute; 3.399 NDT (511 USD &ndash; khoảng 11.7 triệu đồng).</li>\r\n	<li>6 GB + 128 GB gi&aacute; 3.699 NDT (55'],
            ['category_news_id' => 2, 'c_name' => '2019, người Việt sẽ được xem trực tiếp Ngoại Hạng Anh trên Facebook', 'c_content' => '<p>Mới đ&acirc;y, một bức ảnh r&ograve; rỉ cho thấy gi&aacute; b&aacute;n của nhiều phi&ecirc;n bản smartphone Mi MIX 3 &ndash; si&ecirc;u phẩm m&agrave;n h&igrave;nh kh&ocirc;ng viền cạnh sắp ra mắt của&nbsp;Xiaomi.</p>\r\n', 'c_date' => '2018-07-07 21:55:00', 'c_img' => '1530993354giai-bong-da-ngoai-hang-anh_800x450.jpg', 'c_hotnews' => 1, 'c_description' => '<p>Bốn nước sẽ được hưởng quyền lợi n&agrave;y bao gồm: Th&aacute;i Lan, Việt Nam, Campuchia v&agrave; L&agrave;o, bắt đầu từ m&ugrave;a giải 2019 - 2020. Đ&acirc;y l&agrave; động th&aacute;i mới nhất trong nỗ lực ph&aacute;t triển mảng thể thao của Facebook. Năm ngo&aacute;i, họ đ&atilde; thất bại khi tham gia đấu gi&aacute; c&ugrave;ng Star India cho bản quyền giải cricket ở Ấn Độ.</p>\r\n\r\n<p>Ngo&agrave;i ra, danh mục đầu tư v&agrave;o thể thao của &quot;g&atilde; khổng lồ&quot; mạng x&atilde;<'],
            ['category_news_id' => 1, 'c_name' => 'Doanh thu tháng 6 của HTC giảm hơn 67% so với cùng kỳ năm ngoái', 'c_content' => '<p>Mới đ&acirc;y, một bức ảnh r&ograve; rỉ cho thấy gi&aacute; b&aacute;n của nhiều phi&ecirc;n bản smartphone Mi MIX 3 &ndash; si&ecirc;u phẩm m&agrave;n h&igrave;nh kh&ocirc;ng viền cạnh sắp ra mắt của&nbsp;Xiaomi.</p>\r\n', 'c_date' => '2018-07-07 21:57:00', 'c_img' => '15309934201530993420htc-u12-plus_800x450.jpg', 'c_hotnews' => 1, 'c_description' => '<p>Cụ thể, doanh thu th&aacute;ng 6/2018 của&nbsp;HTC&nbsp;đ&atilde; suy giảm rất mạnh trong hơn hai năm qua (kể từ th&aacute;ng 3/2016),&nbsp;chỉ thu được 73.15 triệu USD, giảm 67.64% so với mức 226.1 triệu USD của c&ugrave;ng kỳ năm ngo&aacute;i. Hơn nữa con số n&agrave;y thể hiện sự sụt giảm gần 9% so với th&aacute;ng 5/2018 (thu được 82.35 triệu USD).</p>\r\n'],
            ['category_news_id' => 1, 'c_name' => 'Tin đồn: Nokia X5 sẽ ra mắt ngày 11/7 & quý 3 sẽ có thêm 2 smartphone mới', 'c_content' => '<p>Mới đ&acirc;y, một bức ảnh r&ograve; rỉ cho thấy gi&aacute; b&aacute;n của nhiều phi&ecirc;n bản smartphone Mi MIX 3 &ndash; si&ecirc;u phẩm m&agrave;n h&igrave;nh kh&ocirc;ng viền cạnh sắp ra mắt của&nbsp;Xiaomi.</p>\r\n', 'c_date' => '2018-07-07 21:57:00', 'c_img' => '15309934731530993473coverb_800x450.jpg', 'c_hotnews' => 1, 'c_description' => '<p>Theo như th&ocirc;ng tin r&ograve; rỉ, Nokia X5 sẽ c&oacute; phi&ecirc;n bản 32 GB v&agrave; 64 GB dự kiến được b&aacute;n với gi&aacute; lần lượt l&agrave; 799 Yuan (gần 2.8 triệu đồng) v&agrave; 999 Yuan (khoảng 3.5 triệu đồng ).</p>\r\n\r\n<p>Đ&acirc;y được cho l&agrave; mức gi&aacute; &quot;hấp dẫn&quot; đối với người d&ugrave;ng v&agrave; c&oacute; thể HMD Global sẽ b&aacute;n Nokia X5 tr&ecirc;n thị trường b&ecirc;n ngo&agrave;i với mức gi&aacute; cao hơn so với Trung Quốc.</p>\r\n'],
            ['category_news_id' => 1, 'c_name' => '7 ứng dụng & game hấp dẫn đang được miễn phí cho iPhone, iPad (7/7)', 'c_content' => '<p>Mới đ&acirc;y, một bức ảnh r&ograve; rỉ cho thấy gi&aacute; b&aacute;n của nhiều phi&ecirc;n bản smartphone Mi MIX 3 &ndash; si&ecirc;u phẩm m&agrave;n h&igrave;nh kh&ocirc;ng viền cạnh sắp ra mắt của&nbsp;Xiaomi.</p>\r\n', 'c_date' => '2018-07-07 21:58:00', 'c_img' => '15309934731530993473coverb_800x450.jpg', 'c_hotnews' => 1, 'c_description' => '<p>Snap Markup cho ph&eacute;p bạn đ&aacute;nh dấu hoặc ch&uacute; th&iacute;ch ảnh với c&aacute;c h&igrave;nh dạng kh&aacute;c nhau v&agrave; gửi t&aacute;c phẩm đến bất kỳ đ&acirc;u. Snap Markup cung cấp nhiều h&igrave;nh dạng vẽ kh&aacute;c nhau như h&igrave;nh chữ nhật, h&igrave;nh tam gi&aacute;c, đường thẳng, mũi t&ecirc;n, h&igrave;nh tr&ograve;n, số, đường cong brazier, hiệu ứng Blur, xoay, văn bản, cắt v&agrave; hơn thế nữa.</p>\r\n\r\n<p>Bạn sẽ được thả rơi từ bầu trời v&agrave; h&atilde;n'],
            ['category_news_id' => 1, 'c_name' => 'OPPO A5 màn hình tai thỏ 6.2 inch, camera kép ra mắt', 'c_content' => '<p>Mới đ&acirc;y, một bức ảnh r&ograve; rỉ cho thấy gi&aacute; b&aacute;n của nhiều phi&ecirc;n bản smartphone Mi MIX 3 &ndash; si&ecirc;u phẩm m&agrave;n h&igrave;nh kh&ocirc;ng viền cạnh sắp ra mắt của&nbsp;Xiaomi.</p>\r\n', 'c_date' => '2018-07-07 21:59:00', 'c_img' => '15309934731530993473coverb_800x450.jpg', 'c_hotnews' => 1, 'c_description' => '<p>OPPO A5 c&ograve;n c&oacute; bộ nhớ RAM 4 GB + ROM 64 GB, hỗ trợ khe cắm thẻ nhớ microSD, mặt sau l&agrave; camera k&eacute;p 13 MP + 2 MP, trong khi mặt trước l&agrave; camera 8 MP khẩu độ F/2.2. M&aacute;y ảnh selfie đi k&egrave;m với t&iacute;nh năng l&agrave;m đẹp th&ocirc;ng minh AI, c&oacute; thể nhận dạng 296 điểm tr&ecirc;n khu&ocirc;n mặt.</p>\r\n\r\n<p>OPPO A5 chạy Android 8.1 Oreo với giao diện ColorOS 5.1, pin 4.230 mAh với khả năng ph&aacute;t video 14 giờ hoặc chơi game 11 giờ li&ec'],
            ['category_news_id' => 1, 'c_name' => 'OPPO A3s lộ thông số cấu hình và thiết kế, có thể sắp ra mắt', 'c_content' => '<p>Mới đ&acirc;y, một bức ảnh r&ograve; rỉ cho thấy gi&aacute; b&aacute;n của nhiều phi&ecirc;n bản smartphone Mi MIX 3 &ndash; si&ecirc;u phẩm m&agrave;n h&igrave;nh kh&ocirc;ng viền cạnh sắp ra mắt của&nbsp;Xiaomi.</p>\r\n', 'c_date' => '2018-07-07 22:00:00', 'c_img' => '15309934731530993473coverb_800x450.jpg', 'c_hotnews' => 1, 'c_description' => '<p>Điện thoại kh&ocirc;ng qu&aacute; rộng (ngang 75.6 mm) cho n&ecirc;n c&oacute; thể dễ d&agrave;ng sử dụng bằng một tay. N&uacute;t nguồn v&agrave; khay SIM nằm ở phần khung b&ecirc;n phải c&ograve;n n&uacute;t chỉnh &acirc;m lượng nằm b&ecirc;n tr&aacute;i. OPPO A3s kh&ocirc;ng c&oacute; cảm biến v&acirc;n tay nhưng b&ugrave; lại được trang bị mở kh&oacute;a bằng khu&ocirc;n mặt.</p>\r\n\r\n<p>OPPO A3s dự kiến d&ugrave;ng chip&nbsp;Snapdragon 450 c&ugrave;ng với nh&acirc;n đồ họa Adreno 506, RAM'],
            ['category_news_id' => 2, 'c_name' => 'Giá cổ phiếu BlackBerry vẫn khó tăng trưởng ở thời điểm hiện tại', 'c_content' => '<p>Mới đ&acirc;y, một bức ảnh r&ograve; rỉ cho thấy gi&aacute; b&aacute;n của nhiều phi&ecirc;n bản smartphone Mi MIX 3 &ndash; si&ecirc;u phẩm m&agrave;n h&igrave;nh kh&ocirc;ng viền cạnh sắp ra mắt của&nbsp;Xiaomi.</p>\r\n', 'c_date' => '2018-07-07 22:01:00', 'c_img' => '15309934731530993473coverb_800x450.jpg', 'c_hotnews' => 1, 'c_description' => '<p>Hiện nay, BlackBerry đang cố gắng tập trung v&agrave;o mảng bảo mật, doanh nghiệp v&agrave; cấp giấy ph&eacute;p cho c&aacute;c nh&agrave; sản xuất thiết kế gốc</p>\r\n\r\n<p>Ngo&agrave;i ra, &ocirc;ng John đang hướng BlackBerry tập trung v&agrave;o nhiều phần mềm - dịch vụ kh&aacute;c nhau, đặc biệt l&agrave; những phần mềm thuộc lĩnh vực IoT (Internet of Things) v&agrave; phương tiện xe tự l&aacute;i.</p>\r\n\r\n<p>Tuy nhi&ecirc;n, theo một số nh&agrave; ph&acirc;n t&iacute;ch, ngay cả khi th&amp;a'],
            ['category_news_id' => 2, 'c_name' => 'Tai nghe Apple AirPods vừa có phiên bản mới, giá 399 USD', 'c_content' => '<p>Mới đ&acirc;y, một bức ảnh r&ograve; rỉ cho thấy gi&aacute; b&aacute;n của nhiều phi&ecirc;n bản smartphone Mi MIX 3 &ndash; si&ecirc;u phẩm m&agrave;n h&igrave;nh kh&ocirc;ng viền cạnh sắp ra mắt của&nbsp;Xiaomi.</p>\r\n', 'c_date' => '2018-07-07 22:02:00', 'c_img' => '15309934731530993473coverb_800x450.jpg', 'c_hotnews' => 1, 'c_description' => '<p>Ngo&agrave;i ra, thời gian vận chuyển sản phẩm ước t&iacute;nh mất 3 &ndash; 4 tuần t&ugrave;y thuộc v&agrave;o điểm đến. ColorWare cũng b&aacute;n AirPods bản giới hạn &ndash; Space Gray với gi&aacute; 349 USD (7.93 triệu đồng) v&agrave; nhiều m&agrave;u sắc kh&aacute;c gi&aacute; 299 USD (6.79 triệu đồng).</p>\r\n\r\n<p>Cần biết rằng, Apple dự kiến sẽ ph&aacute;t h&agrave;nh AirPods thế hệ thứ 2 hỗ trợ t&iacute;nh năng &ldquo;Hey Siri&rdquo; ở sự kiện diễn ra v&agrave;o th&aacute;ng 9 tới, b&ec'],
            ['category_news_id' => 2, 'c_name' => 'OPPO A3s lộ thông số cấu hình và thiết kế, có thể sắp ra mắt', 'c_content' => '<p>Mới đ&acirc;y, một bức ảnh r&ograve; rỉ cho thấy gi&aacute; b&aacute;n của nhiều phi&ecirc;n bản smartphone Mi MIX 3 &ndash; si&ecirc;u phẩm m&agrave;n h&igrave;nh kh&ocirc;ng viền cạnh sắp ra mắt của&nbsp;Xiaomi.</p>\r\n', 'c_date' => '2018-07-07 22:03:00', 'c_img' => '15309934731530993473coverb_800x450.jpg', 'c_hotnews' => 1, 'c_description' => '<p>Với mức gi&aacute; mới n&agrave;y, bạn sẽ c&oacute; một thiết bị sở hữu m&agrave;n h&igrave;nh tr&agrave;n viền 5.7 inch HD+ k&egrave;m tấm nền IPS mang lại khả năng hiển thị kh&aacute; tốt, th&iacute;ch hợp cho việc giải tr&iacute;.</p>\r\n\r\n<p>B&ecirc;n cạnh đ&oacute; l&agrave; một cấu h&igrave;nh đủ d&ugrave;ng c&ugrave;ng vi xử l&yacute; Helio P23, RAM 2 GB, bộ nhớ trong 16 GB (hỗ trợ thẻ nhớ mở rộng), 2 nano SIM - hỗ trợ 4G tốc độ cao v&agrave; vi&ecirc;n pin dung lượng 3.180 mAh.</p>\r\n'],
            ['category_news_id' => 2, 'c_name' => 'LG Electronics đã kiếm được', 'c_content' => '<p>Mới đ&acirc;y, một bức ảnh r&ograve; rỉ cho thấy gi&aacute; b&aacute;n của nhiều phi&ecirc;n bản smartphone Mi MIX 3 &ndash; si&ecirc;u phẩm m&agrave;n h&igrave;nh kh&ocirc;ng viền cạnh sắp ra mắt của&nbsp;Xiaomi.</p>\r\n', 'c_date' => '2018-07-07 22:04:00', 'c_img' => '15309934731530993473coverb_800x450.jpg', 'c_hotnews' => 1, 'c_description' => '<p>Trong nửa đầu năm 2018, LG ghi nhận 30.1 ngh&igrave;n tỷ won doanh thu v&agrave; 1.9 ngh&igrave;n tỷ won thu nhập hoạt động, cao nhất&nbsp;từ ​​trước đến nay trong lịch sử của c&ocirc;ng ty. Tuy nhi&ecirc;n, so với qu&yacute; đầu ti&ecirc;n, thu nhập hoạt động của LG giảm 30.4%.</p>\r\n\r\n<p>Mặc d&ugrave; chưa tiết lộ chi tiết về hiệu suất hoạt động của từng mảng, nhưng mảng thiết bị gia dụng được cho l&agrave; đ&atilde; đ&oacute;ng g&oacute;p một phần lớn v&agrave;o việc cải thiện lợi nhuận tổn']
        ]);
    }
}
